# Generated by Django 5.0.2 on 2024-02-15 14:11

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
